spring:
  config:
    activate:
      on-profile: prod

  cors:
    origin: ${CORS_ORIGIN:essaily.site}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_ENDPOINT}?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

  security:
    login:
      success-redirect-uri: ${SECURITY_LOGIN_SUCCESS_REDIRECT_URI}
      not-registered-redirect-uri: ${SECURITY_NOT_REGISTERED_REDIRECT_URI}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

jwt:
  cookie-domain: ${JWT_COOKIE_DOMAIN:essaily.site}